### ISSUE TITLE
what is broken?

### ISSUE THREAD

**Issue by jeffhammond** [nemequ/icc-travis#14]
The [latest build](https://travis-ci.org/nemequ/icc-travis/builds) (7 months ago) is green.  What is broken?  Thanks.

**Comment by nemequ** [comment]
https://github.com/nemequ/icc-travis/issues/3#issuecomment-258502782

This may not be a problem for other license types, so maybe the repository is still useful to some people, but since I can't really use it to check my open source projects I haven't bothered updating to more recent ICC versions.

If anyone knows of a solution I'd definitely be interested, and it would probably motivate me to update the repo to the latest ICC version…  I'm still very interested in CI for ICC.

**Comment by jeffhammond** [comment]
Is it workable to use a license file instead of a key? We’d have to figure out a secure way to store the key but I’m sure there’s a way.

**Comment by jeffhammond** [comment]
Sorry, I didn’t read the other thread. I’m dumb. I need to ask the license people to help. I dropped the ball on that before.
